/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/

package
{
	import flash.display.Sprite;
	
	import org.robotlegs.base.SignalCommandMapTests;
	import org.robotlegs.mvcs.SignalCommandTests;
	import org.robotlegs.mvcs.SignalContextTests;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		
		private var org_robotlegs_mvcs_SignalCommandTests_obj:org.robotlegs.mvcs.SignalCommandTests;
		private var org_robotlegs_mvcs_SignalContextTests_obj:org.robotlegs.mvcs.SignalContextTests;
		private var org_robotlegs_base_SignalCommandMapTests_obj:org.robotlegs.base.SignalCommandMapTests;
	}
}